runtime: nodejs16

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.8
  target_throughput_utilization: 0.8
  max_concurrent_requests: 40

inbound_services:
- warmup

env_variables:
  NODE_ENV: production
  PROJECT_ID: 217939073598
  SECRET_ID: prod-ogx-management
