version: '3.7'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ogx-management
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  dbvol:
