export const SECRET_MANAGER_OPTIONS = Symbol.for('SECRET_OPTIONS');
export const SECRET_MANAGER_CLIENT = Symbol.for('SECRET_MANAGER');
export const CONFIGURATION_SERVICE_TOKEN = 'CONFIGURATION_SERVICE';
