import { ExpaEntity } from 'src/common/entities/expa-entity';

type ExpaEntitySeed = Pick<ExpaEntity, 'name' | 'expaId'>;

export const ExpaEntitySeeds: ExpaEntitySeed[] = [
  { name: 'Aguascalientes', expaId: 207 },
  { name: 'Celaya', expaId: 2062 },
  { name: 'Chihuahua', expaId: 208 },
  { name: 'Ciudad Juárez', expaId: 1168 },
  { name: 'Ciudad Obregón', expaId: 2373 },
  { name: 'Guadalajara', expaId: 1374 },
  { name: 'Guanajuato', expaId: 940 },
  { name: 'IPN', expaId: 1054 },
  { name: 'Irapuato', expaId: 2063 },
  { name: 'ITAM', expaId: 874 },
  { name: 'Tec CEM', expaId: 1077 },
  { name: 'Tec Monterrey', expaId: 1269 },
  { name: 'Tec Santa Fe', expaId: 119 },
  { name: 'Tec Toluca', expaId: 1790 },
  { name: 'La Laguna', expaId: 1672 },
  { name: 'La Salle', expaId: 1193 },
  { name: 'León', expaId: 866 },
  { name: 'Los Mochis', expaId: 2297 },
  { name: 'Michoacán', expaId: 2170 },
  { name: 'Nayarit', expaId: 2298 },
  { name: 'Oaxaca', expaId: 1866 },
  { name: 'Puebla', expaId: 911 },
  { name: 'Querétaro', expaId: 1287 },
  { name: 'Sinaloa', expaId: 552 },
  { name: 'Sonora', expaId: 1671 },
  { name: 'Tabasco', expaId: 69 },
  { name: 'Tampico', expaId: 1865 },
  { name: 'Tijuana', expaId: 2376 },
  { name: 'UAEMEX', expaId: 68 },
  { name: 'UDEM', expaId: 1673 },
  { name: 'UNAM', expaId: 724 },
  { name: 'UP', expaId: 240 },
  { name: 'Veracruz', expaId: 550 },
  { name: 'Zacatecas', expaId: 2134 },
];
