export interface SignupPerson {
  firstName: string;
  lastName: string;
  email: string;
  password: string; // TODO: Autogenerated password?
  phone: string;
}

export interface SignupPersonDto extends SignupPerson {
  state: string;
  allocation: string;
  universityMajor: string;
  semester: string;
  referral: string;
  sdg: string;
  comments: string;
}
