export interface AllocationInfo {
  campus: string;
  product: string;
}

export interface SignupPerson {
  firstName: string;
  lastName: string;
  email: string;
  password: string; // TODO: Autogenerated password?
  phone: string;
}

export interface SignupPersonDto extends SignupPerson {
  allocationInfo: AllocationInfo;
  epInfo: Record<string, string>;
}
